### ISSUE TITLE
metalibm fails to import its own packages successfully?

### ISSUE THREAD

**Issue by pbarfuss** [metalibm/metalibm#86]
Hello,

I'm trying to run metalibm to generate some libm functions, but it fails to load with the following error:
/usr/local/lib/python3.5/dist-packages$ python3 metalibm_functions/ml_cbrt.py --precision binary32 --target x86_sse2 --output s_cbrtf_sse2.c
fatal: Not a git repository (or any of the parent directories): .git
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
Traceback (most recent call last):
  File "ml_cbrt.py", line 51, in <module>
    from metalibm_core.core.ml_function import DefaultArgTemplate
  File "/usr/local/lib/python3.5/dist-packages/metalibm_core/core/ml_function.py", line 81, in <module>
    from metalibm_core.utility.ml_template import DefaultArgTemplate
  File "/usr/local/lib/python3.5/dist-packages/metalibm_core/utility/ml_template.py", line 53, in <module>
    from ..targets import *
  File "/usr/local/lib/python3.5/dist-packages/metalibm_core/targets/__init__.py", line 31, in <module>
    import metalibm_core.targets.common.dummy_asm_target
  File "/usr/local/lib/python3.5/dist-packages/metalibm_core/targets/common/dummy_asm_target.py", line 102, in <module>
    import asmde.allocator as asmde
ImportError: No module named 'asmde'

This is likely a very easy fix but I've not been able to figure out despite a lot of poking around, what am I missing?

Thanks.

**Comment by pbarfuss** [comment]
Issue fixed by running `pip install git+https://github.com/nibrunie/asmde`. This should really be mentioned on the documentation / install instructions page.

**Comment by nibrunie** [comment]
Hello @pbarfuss , thank you for reporting this issue.
Indeed, some dependencies are listed in `requirements.txt` and are directly installed when you install metalibm using pip, but there were not mentionned in a source install. I added a reference to the command `pip install -r requirements.txt` in `README.md`
